run_LCS:
	gcc saxena_varun_pa3_lcs.c -o saxena_varun_pa3_lcs
	
run_Flyod:
	gcc saxena_varun_pa3_floyd.c -o saxena_varun_pa3_floyd

clean_LCS:
	rm -rf saxena_varun_pa3_lcs

clean_Flyod:
	rm -rf saxena_varun_pa3_floyd