run LCS:
	gcc saxena_varun_pa3_lcs.c -o saxena_varun_pa3_lcs
	
run Flyod:
	gcc saxena_varun_pa3_floyd.c -o saxena_varun_pa3_floyd

clean LCS:
	rm -rf saxena_varun_pa3_lcs

clean Flyod:
	rm -rf saxena_varun_pa3_floyd