run:
	gcc saxena_varun_pa5_brute_dynamic_backtrack.c -lm -o saxena_varun_pa5_brute_dynamic_backtrack
	./saxena_varun_pa5_brute_dynamic_backtrack

clean:
	rm -rf saxena_varun_pa5_brute_dynamic_backtrack
	

	
